#!/bin/sh
echo
echo
echo
echo
echo
echo
echo
echo
echo "PLEASE USE SUDO TO RUN THIS INSTALLER/UPDATER"
echo
echo
echo
echo
echo
echo
echo
echo

rm /bin/sh
cp /bin/bash /bin/sh
clear
echo "This script is made by Patrick Pigmans for Servicenet ITF"
echo "Dit Script is gemaakt door Patrick Pigmans voor Servicenet ITF"
sleep 1
echo
echo "if you have  so already please exit this script and type fdisk /dev/mmcblk0 and press the following keys one after another:"
echo "(To exit this script press ctrl + z)"
echo "D, 2, N, P, 2, ENTER, ENTER, W"
echo "then reboot and type resize2fs /dev/mmcblk0p2"
echo "then restart this script"
echo
echo "Als u dit nog niet heb gedaan sluit dit script af en typ het volgende: fdisk /dev/mmcblk0 vervolgens drukt u op de volgende toetsen in volgorde"
echo "(om het script af te sluiten drukt u op ctrl + z)"
echo "D, 2, N, P, 2, ENTER, ENTER, W"
echo "start vervolgens opnieuw op en typ resize2fs /dev/mmcblk0p2"
echo "Start vervolgens het script weer op"
echo
echo
sleep 5

PS3="chose your option (1-4):" 
select name in Shell-updater service-pi-installer-NL service-pi-installer-EN exit
do 
 	break 
done 
echo "You picked $name."
if [ "$name" = "Shell-updater" ]; then
echo 
echo "Starting shell updater"
sh ./.hidden/shell-updater.sh
exit 1
fi

if [ "$name" = "service-pi-installer-NL" ]; then
echo
echo "starting service-pi installer in dutch"
echo "Starten van service-pi installer in het nederlands"
sh ./.hidden/service-pi-install-NL.sh
exit 1
fi

if [ "$name" = "service-pi-installer-EN" ]; then
echo
echo "starting service-pi installer in English"
sh ./.hidden/service-pi-install-EN.sh
exit 1
fi

if [ "$name" = "exit" ]; then
echo
echo "Exitting"
exit 1
fi
